### ISSUE TITLE
Navbar美編

### ISSUE THREAD

**Issue by eason9338** [James-1723/DB_Management#2]
**文字改成ICON**
現在Navbar是用文字當作按鈕，希望可以將它改成適合的Icon，比較視覺化

**搜尋按鈕調整**
現在搜尋按鈕會跑到搜尋欄位下面，希望可以把它改到旁邊，並換成ICON
@wanrou1109

**Comment by wanrou1109** [comment]
沒問題
之前因為修改css結果他跑到下面去了，之後會重新修正

**Comment by eason9338** [comment]
> 沒問題
> 
> 之前因為修改css結果他跑到下面去了，之後會重新修正

可能要改一下整個搜尋欄的width，或調一下margin

**Comment by wanrou1109** [comment]
已完成
