### ISSUE TITLE
Create介面美編

### ISSUE THREAD

**Issue by eason9338** [James-1723/DB_Management#3]
搜尋欄位
現在的輸入匡欄位感覺上下寬度有點稍大，可以調整一下

中文字體
感覺到時候標籤的部分得要設成中文的，因此到時候大部分自行應該都要改成中文，請找一下適合的中文字體
@wanrou1109

**Comment by wanrou1109** [comment]
我之前有下載過的中文字體，我再把他套上去

**Comment by wanrou1109** [comment]
已經修正css，我覺得還行(?
